sudo: required
services:
  - docker

before_install:
  - docker build -t wojciechkrukar/docker-react -f ./client/Dockerfile.dev ./client

script:
  - docker run wojciechkrukar/docker-react npm run test -- --coverage

after_success:
  - docker build -t wojciechkrukar/multi-client ./client
  - docker build -t wojciechkrukar/multi-nginx  ./nginx
  - docker build -t wojciechkrukar/multi-server ./server
  - docker build -t wojciechkrukar/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push  wojciechkrukar/multi-client
  - docker push  wojciechkrukar/multi-nginx
  - docker push  wojciechkrukar/multi-server
  - docker push  wojciechkrukar/multi-worker
